id: P005399
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG12385
  title: སྲིད་པ་རྒྱུད་ཀྱི་ཁ་བྱང་ཆེན་མོ།
  author: ''
  volumes:
    88e7b3bb285e445a853e5ed899c6d427:
      image_group_id: I1KG12403
      title: ''
      volume_number: 1
      total_pages: 228
      base_file: v001.txt
