id: P005399
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12385
  title: སྲིད་པ་རྒྱུད་ཀྱི་ཁ་བྱང་ཆེན་མོ།
  author: ''
  volumes:
    88e7b3bb285e445a853e5ed899c6d427:
      image_group_id: I1KG12403
      title: ''
      volume_number: 1
      total_pages: 228
