id: I59419190
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T20:43:13+00:00'
last_modified: '2022-06-08T02:48:32.579779+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12385
  title: སྲིད་པ་རྒྱུད་ཀྱི་ཁ་བྱང་ཆེན་མོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    494A:
      image_group_id: I1KG12403
      title: ''
      total_pages: 228
      order: 1
      base_file: 494A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
