id: I59419190
legacy_id: P005399
ocr_import_info:
  bdrc_scan_id: W1KG12385
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T20:41:46'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:28:36.031842+00:00'
last_modified: 2022-08-31 11:28:46.525332
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12385
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12385
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྲིད་པ་རྒྱུད་ཀྱི་ཁ་བྱང་ཆེན་མོ།
  author: ལོ་ཙཱ་བ་དྲན་པ་ནམ་མཁའ
statistics:
  ocr_word_mean_confidence_index: 0.756752807441865
  ocr_word_median_confidence_index: 0.8199999928474426
quality: null
bases:
  I1KG12403:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12403
      total_pages: 228
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12403.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.756752807441865
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
